"""
IMPORTANT : all XSD and SOAP responses are written manually (not generated by Spyne lib)
because Spyne doesn't support encodingStyle and other namespaces required by Excel,
check it <http://stackoverflow.com/questions/25046837/the-encodingstyle-attribute-is-not-allowed-in-spyne>
"""

from olapy.stdlib.string cimport Str

cdef Str execute_xsd_s
