CUBE = 'sales'

query1 = """SELECT
         {[Measures].[Amount]} ON COLUMNS
         FROM [sales]"""

query2 = """SELECT
         {[Geography].[Economy].[Partnership]} ON COLUMNS
         FROM [sales]"""

query3 = """SELECT
         non empty {[Geography].[Geo].[Country].members} ON COLUMNS,
         {[Measures].[Amount]} ON ROWS
         FROM [sales]"""

query4 = """SELECT
         {[Geography].[Economy].[Partnership]} ON COLUMNS,
         non empty {[Geography].[Geo].[Country].members} ON ROWS
         FROM [sales]"""

query5 = """SELECT
         {[Geography].[Economy].[Partnership].[EU],
         [Geography].[Economy].[Partnership].[None],
         [Geography].[Economy].[Partnership].[NAFTA]} ON COLUMNS,
         {[Product].[Prod].[Company].[Crazy Development],
         [Product].[Prod].[Company].[Company_test],
         [Product].[Prod].[Company].[test_Development]} ON ROWS
         FROM [sales]"""

# GENERATED BY EXCEL
query6 = """
          SELECT NON EMPTY Hierarchize(AddCalculatedMembers(DrilldownMember({{DrilldownMember({{DrilldownMember({{
          [Time].[Time].[Year].Members}}, {
          [Time].[Time].[Year].[2010]})}}, {
          [Time].[Time].[Quarter].[2010].[Q2 2010]})}}, {
          [Time].[Time].[Month].[2010].[Q2 2010].[May 2010]}))) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME
          ON COLUMNS
          FROM [sales] WHERE ([Measures].[Amount])
          CELL PROPERTIES VALUE, FORMAT_STRING, LANGUAGE, BACK_COLOR, FORE_COLOR, FONT_FLAGS
          """

where = "WHERE [Time].[Calendar].[Day].[May 12,2010]"
