TEST_QUERY_AXIS0 = """[(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[amount]"
   Caption = "amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[product].[product].[company]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[continent].[America]"
   Caption = "America"
   LName = "[geography].[geography].[continent]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[amount]"
   Caption = "amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[product].[product].[company]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[continent].[Europe]"
   Caption = "Europe"
   LName = "[geography].[geography].[continent]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[amount]"
   Caption = "amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[product].[product].[company]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[country].[Europe].[France]"
   Caption = "France"
   LName = "[geography].[geography].[country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[amount]"
   Caption = "amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[product].[product].[company]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[country].[Europe].[Spain]"
   Caption = "Spain"
   LName = "[geography].[geography].[country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[amount]"
   Caption = "amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[product].[product].[company]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[country].[Europe].[Switzerland]"
   Caption = "Switzerland"
   LName = "[geography].[geography].[country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[amount]"
   Caption = "amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[product].[product].[article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[continent].[America]"
   Caption = "America"
   LName = "[geography].[geography].[continent]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[amount]"
   Caption = "amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[product].[product].[article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[continent].[Europe]"
   Caption = "Europe"
   LName = "[geography].[geography].[continent]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[amount]"
   Caption = "amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[product].[product].[article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[country].[Europe].[France]"
   Caption = "France"
   LName = "[geography].[geography].[country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[amount]"
   Caption = "amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[product].[product].[article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[country].[Europe].[Spain]"
   Caption = "Spain"
   LName = "[geography].[geography].[country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[amount]"
   Caption = "amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[product].[product].[article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[country].[Europe].[Switzerland]"
   Caption = "Switzerland"
   LName = "[geography].[geography].[country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[count]"
   Caption = "count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[product].[product].[company]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[continent].[America]"
   Caption = "America"
   LName = "[geography].[geography].[continent]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[count]"
   Caption = "count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[product].[product].[company]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[continent].[Europe]"
   Caption = "Europe"
   LName = "[geography].[geography].[continent]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[count]"
   Caption = "count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[product].[product].[company]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[country].[Europe].[France]"
   Caption = "France"
   LName = "[geography].[geography].[country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[count]"
   Caption = "count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[product].[product].[company]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[country].[Europe].[Spain]"
   Caption = "Spain"
   LName = "[geography].[geography].[country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[count]"
   Caption = "count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[product].[product].[company]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[country].[Europe].[Switzerland]"
   Caption = "Switzerland"
   LName = "[geography].[geography].[country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[count]"
   Caption = "count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[product].[product].[article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[continent].[America]"
   Caption = "America"
   LName = "[geography].[geography].[continent]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[count]"
   Caption = "count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[product].[product].[article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[continent].[Europe]"
   Caption = "Europe"
   LName = "[geography].[geography].[continent]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[count]"
   Caption = "count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[product].[product].[article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[country].[Europe].[France]"
   Caption = "France"
   LName = "[geography].[geography].[country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[count]"
   Caption = "count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[product].[product].[article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[country].[Europe].[Spain]"
   Caption = "Spain"
   LName = "[geography].[geography].[country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[count]"
   Caption = "count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[product].[product]"
   UName = "[product].[product].[article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[product].[product].[article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[product].[product].[company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[product].[product]"
 }, (Member){
   _Hierarchy = "[geography].[geography]"
   UName = "[geography].[geography].[country].[Europe].[Switzerland]"
   Caption = "Switzerland"
   LName = "[geography].[geography].[country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[geography].[geography].[continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[geography].[geography]"
 }, (Member){
   _Hierarchy = "[time].[time]"
   UName = "[time].[time].[year].[2010]"
   Caption = "2010"
   LName = "[time].[time].[year]"
   LNum = "0"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[time].[time].[year]"
   HIERARCHY_UNIQUE_NAME = "[time].[time]"
 }]"""
