TEST_QUERY_AXIS0 = """[(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Amount]"
   Caption = "Amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[Product].[Product].[Company]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Continent].[America]"
   Caption = "America"
   LName = "[Geography].[Geography].[Continent]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Amount]"
   Caption = "Amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[Product].[Product].[Company]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Continent].[Europe]"
   Caption = "Europe"
   LName = "[Geography].[Geography].[Continent]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Amount]"
   Caption = "Amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[Product].[Product].[Company]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Country].[Europe].[France]"
   Caption = "France"
   LName = "[Geography].[Geography].[Country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Geography].[Geography].[Continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Amount]"
   Caption = "Amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[Product].[Product].[Company]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Country].[Europe].[Spain]"
   Caption = "Spain"
   LName = "[Geography].[Geography].[Country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Geography].[Geography].[Continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Amount]"
   Caption = "Amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[Product].[Product].[Company]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Country].[Europe].[Switzerland]"
   Caption = "Switzerland"
   LName = "[Geography].[Geography].[Country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Geography].[Geography].[Continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Amount]"
   Caption = "Amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[Product].[Product].[Article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Product].[Product].[Company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Continent].[America]"
   Caption = "America"
   LName = "[Geography].[Geography].[Continent]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Amount]"
   Caption = "Amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[Product].[Product].[Article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Product].[Product].[Company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Continent].[Europe]"
   Caption = "Europe"
   LName = "[Geography].[Geography].[Continent]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Amount]"
   Caption = "Amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[Product].[Product].[Article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Product].[Product].[Company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Country].[Europe].[France]"
   Caption = "France"
   LName = "[Geography].[Geography].[Country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Geography].[Geography].[Continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Amount]"
   Caption = "Amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[Product].[Product].[Article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Product].[Product].[Company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Country].[Europe].[Spain]"
   Caption = "Spain"
   LName = "[Geography].[Geography].[Country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Geography].[Geography].[Continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Amount]"
   Caption = "Amount"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[Product].[Product].[Article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Product].[Product].[Company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Country].[Europe].[Switzerland]"
   Caption = "Switzerland"
   LName = "[Geography].[Geography].[Country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Geography].[Geography].[Continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Count]"
   Caption = "Count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[Product].[Product].[Company]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Continent].[America]"
   Caption = "America"
   LName = "[Geography].[Geography].[Continent]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Count]"
   Caption = "Count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[Product].[Product].[Company]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Continent].[Europe]"
   Caption = "Europe"
   LName = "[Geography].[Geography].[Continent]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Count]"
   Caption = "Count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[Product].[Product].[Company]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Country].[Europe].[France]"
   Caption = "France"
   LName = "[Geography].[Geography].[Country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Geography].[Geography].[Continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Count]"
   Caption = "Count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[Product].[Product].[Company]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Country].[Europe].[Spain]"
   Caption = "Spain"
   LName = "[Geography].[Geography].[Country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Geography].[Geography].[Continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Count]"
   Caption = "Count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Company].[Crazy Development]"
   Caption = "Crazy Development"
   LName = "[Product].[Product].[Company]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Country].[Europe].[Switzerland]"
   Caption = "Switzerland"
   LName = "[Geography].[Geography].[Country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Geography].[Geography].[Continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Count]"
   Caption = "Count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[Product].[Product].[Article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Product].[Product].[Company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Continent].[America]"
   Caption = "America"
   LName = "[Geography].[Geography].[Continent]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Count]"
   Caption = "Count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[Product].[Product].[Article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Product].[Product].[Company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Continent].[Europe]"
   Caption = "Europe"
   LName = "[Geography].[Geography].[Continent]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Count]"
   Caption = "Count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[Product].[Product].[Article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Product].[Product].[Company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Country].[Europe].[France]"
   Caption = "France"
   LName = "[Geography].[Geography].[Country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Geography].[Geography].[Continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Count]"
   Caption = "Count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[Product].[Product].[Article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Product].[Product].[Company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Country].[Europe].[Spain]"
   Caption = "Spain"
   LName = "[Geography].[Geography].[Country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Geography].[Geography].[Continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }][(Member){
   _Hierarchy = "[Measures]"
   UName = "[Measures].[Count]"
   Caption = "Count"
   LName = "[Measures]"
   LNum = "0"
   DisplayInfo = "0"
   HIERARCHY_UNIQUE_NAME = "[Measures]"
 }, (Member){
   _Hierarchy = "[Product].[Product]"
   UName = "[Product].[Product].[Article].[Crazy Development].[olapy]"
   Caption = "olapy"
   LName = "[Product].[Product].[Article]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Product].[Product].[Company].[Crazy Development]"
   HIERARCHY_UNIQUE_NAME = "[Product].[Product]"
 }, (Member){
   _Hierarchy = "[Geography].[Geography]"
   UName = "[Geography].[Geography].[Country].[Europe].[Switzerland]"
   Caption = "Switzerland"
   LName = "[Geography].[Geography].[Country]"
   LNum = "1"
   DisplayInfo = "131076"
   PARENT_UNIQUE_NAME = "[Geography].[Geography].[Continent].[Europe]"
   HIERARCHY_UNIQUE_NAME = "[Geography].[Geography]"
 }, (Member){
   _Hierarchy = "[Time].[Time]"
   UName = "[Time].[Time].[Year].[2010]"
   Caption = "2010"
   LName = "[Time].[Time].[Year]"
   LNum = "0"
   DisplayInfo = "131076"
   HIERARCHY_UNIQUE_NAME = "[Time].[Time]"
 }]"""
